const ACCOUNT_TYPES = {
    1: "Auto Loan",
    13:"Auto Loan",
    17:"Auto Loan",
    32:"Auto Loan",
    34:"Auto Loan",
    46:"Auto Loan",
    2: "Home Loan",
    3: "Home Loan",
    11: "Home Loan",
    42: "Home Loan",
    4: "Personal Loan",
    5: "Personal Loan",
    6: "Personal Loan",
    12: "Personal Loan",
    14: "Personal Loan",
    15: "Personal Loan",
    23: "Personal Loan",
    24: "Personal Loan",
    38: "Personal Loan",
    41: "Personal Loan",
    45: "Personal Loan",
    60: "Personal Loan",
    69: "Personal Loan",
    71: "Personal Loan",
    7: "Gold Loan",
    70: "Gold Loan",
    8: "Education Loan",
    47: "Education Loan",
    9: "Business Loan",
    18: "Business Loan",
    19: "Business Loan",
    20: "Business Loan",
    33: "Business Loan",
    39: "Business Loan",
    40: "Business Loan",
    51: "Business Loan",
    52: "Business Loan",
    53: "Business Loan",
    54: "Business Loan",
    55: "Business Loan",
    56: "Business Loan",
    57: "Business Loan",
    58: "Business Loan",
    59: "Business Loan",
    61: "Business Loan",
    50: "Business Loan",
    //Credit Card
    10: "Credit Card",
    16: "Credit Card",
    31: "Credit Card",
    35: "Credit Card",
    36: "Credit Card",
    37: "Credit Card",
  };
  
  export default ACCOUNT_TYPES;