
export const jsonData = {
  Enquiry_Reason: {
    1: "Agriculture Loan",
    2: "Auto Loan",
    3: "Business Loan",
    4: "Commercial Vehicle Loans",
    5: "Construction Equipment loan",
    6: "Consumer Loan",
    7: "Credit Card",
    8: "Education Loan",
    9: "Leasing",
    10: "Loan against collateral",
    11: "Microfinance",
    12: "Non-funded Credit Facility",
    13: "Personal Loan",
    14: "Property Loan",
    15: "Telecom",
    16: "Two/Three Wheeler Loan",
    17: "Working Capital Loan ",
    18: "Consumer Loan",
    19: "Credit Review",
    99: "Others",
  },
  Finance_Purpose: {
    1: "Agricultural Machinery",
    2: "Animal Husbandry",
    3: "Aquaculture",
    4: "Biogas Plant",
    5: "Crop Loan",
    6: "Horticulture",
    7: "Irrigation System",
    8: "New Car",
    9: "Overdraft against Car",
    10: "Used Car",
    11: "General",
    12: "Small & Medium Business",
    13: "Professionals",
    14: "Trade",
    15: "Bus",
    16: "Tempo",
    17: "Tipper",
    18: "Truck",
    20: "Forklift",
    21: "Wheel Loaders",
    22: "Consumer Search",
    23: "Credit Card",
    24: "Fleet Card",
    25: "For Working Executives",
    26: "Study Abroad",
    27: "Study in India",
    28: "Leasing",
    29: "Bank Deposits",
    30: "Gold",
    31: "Govt. Bonds / PPF / NSC / KVP / FD",
    32: "Shares and Mutual Funds",
    33: "Business Loan",
    34: "Housing Loan",
    35: "Personal Loan",
    36: "Agriculture",
    37: "General",
    38: "Small Business",
    39: "Computers / Laptops",
    40: "Consumer Durables",
    41: "Marriage / Religious Ceremonies",
    42: "Travel",
    43: "Balance Transfer",
    44: "Home Improvement / Extension",
    45: "Land",
    46: "Lease Rental Discounting",
    47: "Loan against Property",
    48: "New Home",
    49: "Office Premises",
    50: "Under construction",
    51: "Broadband",
    52: "Landline",
    53: "Mobile",
    54: "Three Wheeler",
    55: "Two Wheeler",
    56: "Cash credit facility",
    57: "Overdraft",
    58: "Term Loan",
    60: "Microfinance Detailed Report",
    61: "Summary Report",
    62: "VB OLM Retrieval Service",
    63: "Account Review",
    64: "Retro Enquiry",
    65: "Locate Plus",
    66: "Consumer Search Loan",
    67: "Indicative Report",
    68: "Consumer Search Loan",
    69: "Bank OLM Retrieval Service",
    70: "Adviser Liability",
    71: "Secured (Account Group for Portfolio Review response)",
    72: "Unsecured (Account Group for Portfolio Review response)",
    99: "Others",
  },
  Terms_Frequency: {
    D: "Daily",
    P: "Single payment loan",
    W: "Weekly",
    B: "Bi-Weekly",
    E: "Semi-monthly",
    M: "Monthly",
    L: "2 monthly (bimonthly)",
    Q: "3 monthly (quarterly)",
    T: "Triannualy",
    HY: "Half-Yearly",
    Y: "Yearly",
    X: "Variable",
    U: "Unknown",
    OD: "On-demand",
    BP: "Bullet Payment",
  },
  Gender_Code: {
    1: "Male",
    2: "Female",
    3: "Transgender",
  },
  State: {
    "01": "JAMMU and KASHMIR",
    "02": "HIMACHAL PRADESH",
    "03": "PUNJAB",
    "04": "CHANDIGARH",
    "05": "UTTRANCHAL",
    "06": "HARAYANA",
    "07": "DELHI",
    "08": "RAJASTHAN",
    "09": "UTTAR PRADESH",
    10: "BIHAR",
    11: "SIKKIM",
    12: "ARUNACHAL PRADESH",
    13: "NAGALAND",
    14: "MANIPUR",
    15: "MIZORAM",
    16: "TRIPURA",
    17: "MEGHALAYA",
    18: "ASSAM",
    19: "WEST BENGAL",
    20: "JHARKHAND",
    21: "ORRISA",
    22: "CHHATTISGARH",
    23: "MADHYA PRADESH",
    24: "GUJRAT",
    25: "DAMAN and DIU",
    26: "DADARA and NAGAR HAVELI",
    27: "MAHARASHTRA",
    28: "ANDHRA PRADESH",
    29: "KARNATAKA",
    30: "GOA",
    31: "LAKSHADWEEP",
    32: "KERALA",
    33: "TAMIL NADU",
    34: "PONDICHERRY",
    35: "ANDAMAN and NICOBAR ISLANDS",
    36: "TELANGANA",
    99: "APO Address",
  },
  Marital_Status: {
    blank: "",
    1: "Single",
    2: "Married",
    4: "Divorced",
    3: "Widow/Widower",
  },
  Employment_Status: {
    blank: "blank",
    S: "Salaried",
    N: "Non-Salaried",
    E: "Self-employed",
    P: "Self-employed Professional",
    U: "Unemployed",
  },
  Account_Type: {
    blank: "",
    1: "AUTO LOAN",
    2: "HOUSING LOAN",
    3: "PROPERTY LOAN",
    4: "LOAN AGAINST SHARES/SECURITIES",
    5: "PERSONAL LOAN",
    6: "CONSUMER LOAN",
    7: "GOLD LOAN",
    8: "EDUCATIONAL LOAN",
    9: "LOAN TO PROFESSIONAL",
    10: "CREDIT CARD",
    11: "LEASING",
    12: "OVERDRAFT",
    13: "TWO-WHEELER LOAN",
    14: "NON-FUNDED CREDIT FACILITY",
    15: "LOAN AGAINST BANK DEPOSITS",
    16: "FLEET CARD",
    17: "Commercial Vehicle Loan",
    18: "Telco - Wireless",
    19: "Telco - Broadband",
    20: "Telco - Landline",
    23: "GECL Secured",
    24: "GECL Unsecured",
    31: "Secured Credit Card",
    32: "Used Car Loan",
    33: "Construction Equipment Loan",
    34: "Tractor Loan",
    35: "Corporate Credit Card",
    36: "Kisan Credit Card",
    37: "Loan on Credit Card",
    38: "Prime Minister Jaan Dhan Yojana - Overdraft",
    39: "Mudra Loans - Shishu / Kishor / Tarun",
    40: "Microfinance - Business Loan",
    41: "Microfinance - Personal Loan",
    42: "Microfinance - Housing Loan",
    43: "Microfinance - Others",
    44: "Pradhan Mantri Awas Yojana - Credit Link Subsidy Scheme MAY CLSS",
    45: "P2P Personal Loan",
    46: "P2P Auto Loan",
    47: "P2P Education Loan",
    51: "BUSINESS LOAN - GENERAL",
    52: "BUSINESS LOAN -PRIORITY SECTOR - SMALL BUSINESS",
    53: "BUSINESS LOAN -PRIORITY SECTOR - AGRICULTURE",
    54: "BUSINESS LOAN -PRIORITY SECTOR - OTHERS",
    55: "BUSINESS NON-FUNDED CREDIT FACILITY - GENERAL",
    56: "BUSINESS NON-FUNDED CREDIT FACILITY - PRIORITY SECTOR - SMALL BUSINESS",
    57: "BUSINESS NON-FUNDED CREDIT FACILITY - PRIORITY SECTOR - AGRICULTURE",
    58: "BUSINESS NON-FUNDED CREDIT FACILITY - PRIORITY SECTOR - OTHERS",
    59: "BUSINESS LOANS AGAINST BANK DEPOSITS",
    60: "Staff Loan",
    61: "Business Loan - Unsecured",
    "00": "Others",
    50: "Business Loan - Secured",
    69: "Short Term Personal Loan [Unsecured]",
    70: "Priority Sector Gold Loan [Secured]",
    71: "Temporary Overdraft [Unsecured]",
  },
  Account_Status: {
    "00": "No Suit Filed",
    89: "Wilful default",
    93: "Suit Filed(Wilful default)",
    97: "Suit Filed(Wilful Default) and Written-off",
    30: "Restructured",
    31: "Restructured Loan (Govt. Mandated)",
    32: "Settled",
    33: "Post (WO) Settled",
    34: "Account Sold",
    35: "Written Off and Account Sold",
    36: "Account Purchased",
    37: "Account Purchased and Written Off",
    38: "Account Purchased and Settled",
    39: "Account Purchased and Restructured",
    40: "Status Cleared",
    41: "Restructured Loan",
    42: "Restructured Loan (Govt. Mandated)",
    43: "Written-off",
    44: "Settled",
    45: "Post (WO) Settled",
    46: "Account Sold",
    47: "Written Off and Account Sold",
    48: "Account Purchased",
    49: "Account Purchased and Written Off",
    50: "Account Purchased and Settled",
    51: "Account Purchased and Restructured",
    52: "Status Cleared",
    53: "Suit Filed",
    54: "Suit Filed and Written-off",
    55: "Suit Filed and Settled",
    56: "Suit Filed and Post (WO) Settled",
    57: "Suit Filed and Account Sold",
    58: "Suit Filed and Written Off and Account Sold",
    59: "Suit Filed and Account Purchased",
    60: "Suit Filed and Account Purchased and Written Off",
    61: "Suit Filed and Account Purchased and Settled",
    62: "Suit Filed and Account Purchased and Restructured",
    63: "Suit Filed and Status Cleared",
    64: "Wilful Default and Restructured Loan",
    65: "Wilful Default and Restructured Loan (Govt. Mandated)",
    66: "Wilful Default and Settled",
    67: "Wilful Default and Post (WO) Settled",
    68: "Wilful Default and Account Sold",
    69: "Wilful Default and Written Off and Account Sold",
    70: "Wilful Default and Account Purchased",
    72: "Wilful Default and Account Purchased and Written Off",
    73: "Wilful Default and Account Purchased and Settled",
    74: "Wilful Default and Account Purchased and Restructured",
    75: "Wilful Default and Status Cleared",
    76: "Suit filed (Wilful default) and Restructured",
    77: "Suit filed (Wilful default) and Restructured Loan (Govt. Mandated)",
    79: "Suit filed (Wilful default) and Settled",
    81: "Suit filed (Wilful default) and Post (WO) Settled",
    85: "Suit filed (Wilful default) and Account Sold",
    86: "Suit filed (Wilful default) and Written Off and Account Sold",
    87: "Suit filed (Wilful default) and Account Purchased",
    88: "Suit filed (Wilful default) and Account Purchased and Written Off",
    94: "Suit filed (Wilful default) and Account Purchased and Settled",
    90: "Suit filed (Wilful default) and Account Purchased and Restructured",
    91: "Suit filed (Wilful default) and Status Cleared",
    13: "CLOSED",
    14: "CLOSED",
    15: "CLOSED",
    16: "CLOSED",
    17: "CLOSED",
    12: "CLOSED",
    11: "ACTIVE",
    71: "ACTIVE",
    78: "ACTIVE",
    80: "ACTIVE",
    82: "ACTIVE",
    83: "ACTIVE",
    84: "ACTIVE",
    DEFAULTVALUE: "ACTIVE",
    21: "ACTIVE",
    22: "ACTIVE",
    23: "ACTIVE",
    24: "ACTIVE",
    25: "ACTIVE",
    131: "Restructured due to natural calamity",
    130: "Restructured due to COVID-19",
    132: "Post Write Off Closed",
    133: "Restructured & Closed",
    134: "Auctioned & Settled",
    135: "Repossessed & Settled",
    136: "Guarantee Invoked",
    137: "Entity ceased while account was open",
    138: "Entity ceased while account was closed",
  },
  AccountHoldertypeCode: {
    blank: "",
    1: "Individual",
    2: "Joint",
    3: "Authorized User",
    7: "Guarantor",
    Z: "Deceased",
  },
  Identification_Number: {
    PU: "BANK",
    PV: "BANK",
    FO: "BANK",
    RR: "BANK",
    CO: "BANK",
    NB: "NBFC",
    HF: "HOUSING FINANCE COMPANY",
    TE: "TELECOM",
    IN: "INSURANCE",
    MF: "MICROFINANCE INSTITUTION",
    CR: "CREDIT RATING AGENCY",
  },
  Payment_History_Profile: {
    N: "Value not available",
    0: "0–29 days past the due date",
    1: "30-59 days past the due date",
    2: "60-89 days past the due date",
    3: "90-119 days past the due date",
    4: "120-149 days past the due date",
    5: "150-179 days past the due date",
    6: "180 or more days past the due date",
    S: "Asset Classification is Standard",
    B: "Asset Classification is Substandard",
    D: "Asset Classification is Doubtful",
    M: "Asset Classification is Special Mention Account",
    L: "Asset Classification is Loss",
  },
  Asset_Classification: {
    N: "Value not available",
    0: "0–29 days past the due date",
    1: "30-59 days past the due date",
    2: "60-89 days past the due date",
    3: "90-119 days past the due date",
    4: "120-149 days past the due date",
    5: "150-179 days past the due date",
    6: "180 or more days past the due date",
    S: "Asset Classification is Standard",
    B: "Asset Classification is Substandard",
    D: "Asset Classification is Doubtful",
    M: "Asset Classification is Special Mention Account",
    L: "Asset Classification is Loss",
  },
  SuitFiledWillfulDefaultWrittenOffStatus: {
    "00": "Restructured",
    "01": "Suit Filed",
    "02": "Wilful Default",
    "03": "Suit Filed (Wilful Default)",
    "04": "Written Off",
    "05": "Suit Filed & Written Off",
    "06": "Wilful Default & Written Off",
    "07": "Suit Filed (Wilful Default) & Written Off",
    "08": "Settled",
    "09": "Post (WO) Settled",
  },
  SuitFiled_WillfulDefault: {
    0: "No Suit Filed",
    1: "Suit Filed",
    2: "Wilful Default",
    3: "Suit Filed (Wilful Default)",
  },
  Written_off_Settled_Status: {
    0: "Restructured Loan",
    1: "Restructured Loan (Govt. Mandated)",
    2: "Written-off",
    3: "Settled",
    4: "Post (WO) Settled",
    5: "Account Sold",
    6: "Written Off and Account Sold",
    7: "Account Purchased",
    8: "Account Purchased and Written Off",
    9: "Account Purchased and Settled",
    10: "Account Purchased and Restructured",
    11: "Restructured due to Natural Calamity",
    12: "Restructured due to COVID-19",
    13: "Post Write Off Closed",
    14: "Restructured & Closed",
    15: "Auctioned & Settled",
    16: "Repossessed & Settled",
    17: "Guarantee Invoked",
    99: "Clear Existing Status",
  },
  Type_of_Collateral: {
    99: "No Collateral",
    11: "Property",
    12: "Gold",
    13: "Shares",
    14: "Saving Account and Fixed Deposit",
    "05": "Multiple Securities",
    "06": "Others",
  },
  Portfolio_Type: {
    F: "Microfinance",
    I: "Instalment Loans",
    M: "Mortgage Loan",
    L: "Open Lines of Credit",
    R: "Revolving Credit",
    S: "Single Payment Loans",
  },
};

export const partnerCode = {
  finezza: process.env.REACT_APP_FINEZZA_SECRET_KEY,
  onsurity: process.env.REACT_APP_ONSURITY_SECRET_KEY,
  hyperverge: process.env.REACT_APP_HYPERVERGE_SECRET_KEY,
  jodo: process.env.REACT_APP_JODO_SECRET_KEY,
  instafinancials: process.env.REACT_APP_INSTAFINANCIALS_SECRET_KEY,
  velocity: process.env.REACT_APP_VELOCITY_SECRET_KEY,
  knightfintech: process.env.REACT_APP_KNIGHTFINTECH_SECRET_KEY,
  signzy: process.env.REACT_APP_SIGNZY_SECRET_KEY,
  finbud: process.env.REACT_APP_FINBUD_SECRET_KEY,
  sensei: process.env.REACT_APP_SENSEI_SECRET_KEY,
  canpe: process.env.REACT_APP_CANPE_SECRET_KEY,
  theloanjunction: process.env.REACT_APP_THELOANJUNCTION_SECRET_KEY,
  bulkpe: process.env.REACT_APP_BULKPE_SECRET_KEY,
  maximy: process.env.REACT_APP_MAXIMY_SECRET_KEY,
  hoogmatic: process.env.REACT_APP_HOOGMATIC_SECRET_KEY,
  finstack: process.env.REACT_APP_FINSTACK_SECRET_KEY,
  paisapulse: process.env.REACT_APP_PAISA_SECRET_KEY,
  invincible: process.env.REACT_APP_INVINCIBLE_SECRET_KEY,
  addpay: process.env.REACT_APP_ADDPAY_SECRET_KEY,
  circlepe: process.env.REACT_APP_CIRCLEPE_SECRET_KEY,
  maxmy: process.env.REACT_APP_MAXMY_SECRET_KEY,
  moolpay: process.env.REACT_APP_MOOLPAY_SECRET_KEY,
  mxontech: process.env.REACT_APP_MXONTECH_SECRET_KEY,
  pop: process.env.REACT_APP_POP_SECRET_KEY,
  finb: process.env.REACT_APP_FINB_SECRET_KEY,
  gruhfin: process.env.REACT_APP_GRUHFIN_SECRET_KEY,
};

